import './models/summary.dart';

const SUMMARY = const [
  Summary(
    id: 'l1',
    body:
        'In the poem The Grandmother, the American-Indian poet, Ray Young Bear, draws a picture of his grandmother, all-loving, all-inspiring. His grandmother would wear a purple scarf round her head for warmth, and she would go to market with a plastic shopping bag in her hand. Her shape was also quite remarkable. If the poet saw her forma a long distance, he could tell that she was his grandmother. She would come home working in the field and wash her hands. They were wet and had the smell of roots. She would put her hands on his head and caress it lovingly. Although they were wet, they would be warm out of love. Before he looked at her face, the smell and warmth-would make him guess that it was his grandmother.\n\n'
        'Sometimes the poet would go to her grave. He would imagine having heard a voice coming from the tombstone. He could feel to be his grandmother. He could feel that her words were moving smoothly inside him like a stream. They would inspire him. In his sad life he would find a faint glimpse of hope. He would remember the winter night when they were shivering with cold. His grandmother would wake up and try to move the fire which was covered with thick ashes, and he would see her from his bed and hope that he would warm his body by the open fire.\n\n'
        ' The poem expresses not only poet’s love and respect towards his grandmother but uses grandmother as an epitome for native America. The poem has tried to pay tribute to his Native American grandmother. The poem is rich in use of symbols and images that brings out a picture of typical Mesquaki grandmother and her native culture. The grandmother portrayed in the poem appears to be all loving and affectionate. The poet feels a kind of loss for his grandmother and expresses his strong desire to be with her.\n\n'
        'The poet has used his all sensory perceptions to understand the greatness of his grandmother. In the first part of the poem, poet uses his eyes to identify his grandmother’s shape, her purple scarf, and a plastic shopping bag. In the middle part of the poem, he uses his skin and nose to recognize his grandmother’s warm and damp hand on his head, and he could get ancestral smell from her. In the last part of the poem, poet uses his good sense of his ears to hear her words in the land of his origin. In this way poet has successfully drawn a picture of his grandmother by various images appeal to all senses.\n\n'
        'The verse of the poem “I’d know her words would flow inside me like the light of someone sharing ashes from a sleeping fire night,” clarifies the poet’s feelings. He means that wisdom got from his grandmother helps to search for identity of Native American people. He finds his grandmother a great teacher for the depth of past and the lesson of life in the present time. The poet also finds his grandmother all-loving and all-inspiring. ‘Warm and damp’ shows how deeply, she loved him and “her words flow inside me like the light” shows how poet is inspired by her.\n\n',
  ),
  Summary(
      id: 'l2',
      body:
          'W. B. Yeats, the greatest English poet of 20th century, presents the reminiscences of his eventful young age and contrasts them with his present pathetic old life in the poem, \“The Lamentation of the Old Pensioner.\"The title suggests that the poet is a Pensioner. It means he must be very old and is living a retired life. He says whenever he is caught in rain he takes shelter under a broken tree. The broken tree can not protect him from the rain. Here, one must note the point that in England it rains during winter. It means he is deprived of a reliable shelter, when he needs it most. But it was not always the case with him. When he was young, he used to sit nearest to the fire, which warmed and comforted him. You can’t light fire in rain outside. It means he had reliable place to live in when he was young. Not only that, the cosy parlour of the poet always used to be full of the livelier company of his friends who talked about love and politics. But today, he misses them as “Time” has taken away all his friends leaving him old and isolated.\n\n'
          'He sees some mischievous boys making weapons for some conspiracy. These ‘rascals’ are sure to create chaos in the society through some barbarous activities. But the poet is not concerned about the possible anarchy in the society. He is sad as the time has transfigured him.\n\n'
          'The poet laments that the time has made him ugly like a broken tree and therefore, no woman shows interest in him. However, the poet consoles himself that “the beauties that he loved” are still fresh in his memory. He holds the “Time” a culprit, who has taken away his shelter, friends, youth, energy, and charm and wants to spit on its face in disgust for his metamorphosis.\n\n'),
  Summary(
      id: 'l3',
      body:
          'The poem “Full Fathom Five Thy Father Lies” is a song sung by the Spirit Ariel in Shakespeare’s play “The Tempest”. The Spirit sings this song to Ferdinand, the prince of Naples, who mistakenly thinks that his father is drowned.\n\n'
          'The speaker of this poem is Ariel who is very powerful spirit of wind who flies lightly and invisibly playing music and singing songs. Here he sings the song about the death of Ferdinand’s father. According to him, Ferdinand’s father lies thirty feet below the surface of the sea. Ferdinand is very worried about the death of his father. Giving him sympathy Ariel says that his father has got quite meaningful death. His body is not decayed. Every part of his body has been changed into something beautiful, valuable and strange. His eyes are transformed into pearls and bones are’ changed into coral. The sea nymphs welcome his death by ringing the death bell “Ding-dong” every hour.\n\n'
          'In this poem, the spirit Ariel has presented very artful and melodious description about the death of Ferdinand’s father. The prince of Naples is worried thinking that his father is drowned. He is very sad about the meaningless death of his father. However, Ariel gives him sympathy by making the death meaningful through his powerful and magical description. He says that nothing of the dead body has decayed or rotten wastefully. Everything of the dead body is changed into meaningful and precious objects at the bottom of the sea. Ariel finally requests Ferdinand to listen to the death-bell rung by the sea nymphs to welcome his father’s beautiful and meaningful death.\n\n'),
  Summary(
      id: 'l4',
      body:
          'The poem, “Travelling through the Dark”, depicts the internal conflict between the mind, a sense of responsibility, and heart, the compassion, of the narrator. At the same time, through the symbolic “Dark” of the title the poet is able to portray that the growing affinity of human with machine is tempting them to collide with the nature, a collision which will be threatening for all the living species on the planet, not only a doe.\n\n'
          'On a dark night, the narrator was driving his car on Wilson River road. At the edge of the river he found a dead deer. His common sense told him to roll that deer into the gorge because the road was narrow and a slight carelessness might call for more accidents. He stopped his car and went near to it. It was a doe and had been dead. But when he dragged it he found that it was pregnant.\n\n'
          'When he observed its belly closely, he sensed that the fawn inside it must be alive. But he also knew that it could not be born. The tragic fate of the fawn made him emotional. It was difficult for him to throw the body into the gorge because it would kill the baby instantly.\n\n'
          'His dilemma and inactness blocked the street. He listened the people getting restless as everybody was in hurry to go. They immediately wanted the road to be opened. The narrator thought very deeply and concluded that it wasn’t practical to leave the dead body of the doe on the street. It could make more accidents. Therefore, he threw it into the gorge and chose to perform his duty.\n\n'),
  Summary(
      id: 'l5',
      body:
          'In his sonnet “God’s Grandeur” the poet G.M Hopkins praises the magnificence and glory of God. He describes the majestic deeds of God. He claims that God is omnipresent and omnipotent. The good deeds on earth are also the results of these qualities of God. Though human beings continuously destroy nature, it is never spent.\n\n'
          'The world is full of the greatness of God. Due to His greatness, the world shines like ‘a shook foil’. It gathers to a greatness, as it is full of resources. Despite this fact, human beings act adversely. They don’t follow the commands of God; rather they function to destroy the world. Earlier generations destroyed the earth and so is the case with the present generation. People are more interested in materialist gain and possessions than in celebrating the glory of a loving, merciful, heavenly Father. They act as if they are not rational creatures. As a result of their deed, the earth has become dry; it has the smell of human beings instead of its natural smell. Indeed the earth has reached to the verge of destruction. Nevertheless, the world is not completely destroyed. Because of the freshness that is inside things, nature keeps on regenerating. The sun sets in the evening only to reappear in the morning. These happenings are the results of the god’s protection. He protects the earth just like a bird broods over the eggs.\n\n'
          'Though the world is infused with the glory of God and Christ offered His body to be crucified, mankind does not live in awe of God, but imposes darkness on itself by running endlessly. Even so, despite humanity’s shortcomings, God is most capable of perfect love and embraces the world anyway. The poet is of the opinion that human beings acts are always directed towards destruction: knowingly or unknowingly. But God loves all the creatures of the world, so he works for the benefit of the creatures without any hope of benefit or profit. The poet inspires people to grow faith in God.\n\n'),
  Summary(
      id: 'l6',
      body:
          '“About Love” is a famous Russian story written by a famous story-writer, Anton Chekhov. In the story, Chekhov presents the difference between three love stories and tries to prove that “Love” like that is not bound by conjugal relations. He views that love is true and spiritual. Happiness, unhappiness, morality, sin, virtue, social status, class, prestige etc. have nothing to do with love. Alyohin is the narrator in this story. He had been living as a poor farmer at Sofyino since he graduated from the university. The story begins when the narrator and his two guests-Bufkin and Ivan were having breakfast in a country house. Alyohin told about the violent love affair between his two servants Nikanor and Pelageya. According to the narrator, pelageya didn’t want to marry Nikanor but she was ready to live with him just so. On the other hand, Nikanor couldn’t stay with her before marriage for religious reasons. Alyohin says that love is a hindrance and a source of dissatisfaction and irritation. To justify his statement, he began his own story.\n\n'
          'Alyohin had to work hard at Sofyino to pay off his debt as his father had spent a lot of money on his education by mortgaging the land. Though he was a landowner, Alyohin had to work hard in the farm with his servants. Many years before, he had been elected honorary justice for peace and sometimes he had to go to the town to participate in the court session. Unexpectedly, one of his friends, Luganovich invited him for dinner. There, he was very much attracted by the young and beautiful Ana Alexeyevna, the wife of Luganovich. In the later days, he frequently visited her and they spent much time together flaking for hours and going to the theatre. Though they couldn’t miss the company of each other, they didn’t express their desires, love and feedings. They hid feelings fearing that it would ruin both of their lives.\n\n'
          'At last, as a result of unexpressed feelings, Anna had got mental sickness and she had to go to Crimea for treatment. Many people gathered at the railway station to say goodbye to Anna. When the train started to move, Alyohin ran to Anna with her basket which she had forgotten. Their emotional eyes met together and their spiritual strength couldn’t stop them falling in each other’s arms. They kissed each other and expressed their deep love. However, they parted forever and Alyohin returned to his farm land (village) being sad and he would never meet her again in his life. The true love of Alyohin is the means of living. The moment of her memory often relieved Alyohin in his life.\n\n'),
  Summary(
      id: 'l7',
      body:
          'The boy, with his uncle, was sitting in their room when the boy’s uncle’s friends came there. Their coming had the aim of deciding the date for an outing. They said that they had collected fund and liquor for an outing. Afterward, the uncle’s friends returned back to their home. The next day they came with the list of names for uncle’s acceptance. He read the whole list and accepted all the names. Then there was his wife with china dog.\n\n'
          'She threatened him that she would go to her mother’s house if he did not cancel the program. In anger, she asked him to choose either her or outing. The uncle said that he preferred outing. On Saturday morning the uncle’s wife left the house. She had written a note to her husband in which she had asked him to put off shoes before going to bed. At about eight the uncle’s friend came to his house with a charabanc. They became ready to go for an outing. As they drove off, the women of the village peeped out from windows and boys bid them good-bye. No sooner had they crossed the village then reached a public house. The uncle asked the boy to look after the charra whereas they went inside. A little later a man came and asked for the way to the pub. The boy took the man there. Inside the pub, he saw his uncle and his friends drinking, breaking the glasses and talking nonsense. The boy did not remain there. He was afraid of the situation. Afterwards, the uncle and his friends came out and got into the charra.\n\n'
          'Then they reached a river where they all got down and played with water. From that time onwards, they forget the idea of Porthcrawl. By the evening they reached to place called Hermit’s nest. There they decided to rest and enjoy drinking. They drank so much rum that they could not control their sense. They later made the decision to return back. On the way home, they rested in a field and sat in a circle. They continued drinking there too.\n\n'),
  Summary(
      id: 'l8',
      body:
          'This story is written by applying stream of consciousness technique. It explains how a boy deepens his observation and grows from an ordinary boy to an assertive young man.\n\n'
          'When the story starts we find the boy is already grown into assertive man, when he asserts, “Now they are going to see who I am.” But in the very next line we are made familiar about the past events through retrospective technique.\n\n'
          'Four years ago in March, the boy saw a huge ship, which lost its way, crushed to a rock and sank. There were no lights on the ship. Neither had it appeared in the light of the lighthouse. He could only see the ship in extreme darkness. Our common sense tells that we can see an object only if it is luminous or it is illuminated. Thus, it is clear that it was just an imagination of the boy. He was himself not sure about that vision for the first time and didn’t tell anybody about that.\n\n'
          'In the following March, he saw a similar ship again. This time he told his mother about it. His mother didn’t believe him. Rather, she thought the boy became lunatic and lamented for three weeks. However, she assured him that she would go and look at the ship if it came again. But before the arrival of the ship, she died.\n\n'
          'When the ship appeared in March again, the boy called the villagers to see that ship. But as there wasn’t any ship and they beat the boy for telling lie. After that the boy decided if the ship came next time he would show everybody how big the ship was.\n\n'
          'The ship appeared in the fourth March too. This time the boy led the ship with a stolen lamp in a small boat. The light of the lamp helped the ship to correct it way and it followed the boy. The boy brought the ship to the village. The gigantic ship was 97 times longer than the village and 20 times taller than the church. The boy imagined that its loud siren had woken the whole village, and they were looking at the ship in disbelieve. This would help him to prove his worth and who he was.\n\n'
          'Actually it is the story about the powerful imagination of the boy. Sometimes a person’s creative power becomes so sharp that he can see his vision in concrete form. A normal mind with limited power of creativity hardly sees such picture.\n\n'),
  Summary(
      id: 'l9',
      body:
          '“The Tell-Tale Heart” is a psychological and strange story written by Edger Allan Poe. The unnamed narrator of the story is probably a boy who lives in an old man’s house. He is suffering from the nervous disease. He is over sensitive to hearing. According to him, the old man has the eye like vulture. The narrators fears from the eyes of old man. When the eye of the old man falls upon the narrator, his blood becomes cold. To overcome these fear, the narrator wants to kill the old man to destroy the eye. Every night, the boy tries to kill the old man but becomes unsuccessful. On the eighth night, when he opens the door of the old man, he suddenly has a feeling of power. He kills the old man to be free from the eye of vulture He cuts off the head and arms of the old man and hides the dead body under the wooden floor. The boy neglects to remove the watch from the wrist of the old man. He leaves no sign of blood and other proofs of murder.\n\n'
          'After the murder the three police officers have arrived to the house for investigation. They search the house but find no evidence of the murder. The narrator hides his inner feelings and behaves very politely and pleasantly to the police officers. He talks with a smile and shows the policemen the treasure (money) and the room of the old man. He answers the questions of the officers very carefully and happily. They believe the narrator and they talk in a friendly way about other things. Then suddenly, the boy hears the tick-tick sound that comes actually from the watch of the old man. However, the narrator mistakes it for the heart beating of the dead body. The boy tries to kill the sound by talking loudly but the sound becomes louder and louder. He becomes angry and excited. He throws his chairs across the room. The policemen still talk and smile. The boy thinks that they have already known the hidden truth. He realizes that they are making fun of him, and then in his mad sense, the narrator confesses his crime. He says that he has murdered the old man and hidden the dead body under the wooden floor.\n\n'
          'Finally, the boy kills an innocent old man because of his madness. His nervous disease leads him to be a murderer. Again, because of his mad sense, he mistakes the clock sound of the watch to be the heart beating of the dead body and thus he confesses his guilt in front of police officers.\n\n'),
  Summary(
      id: 'l10',
      body:
          'Once in a time, nearby the large forest, a poor woodcutter lived with his wife and two children. The son’s name was called Hansel and the daughter was Gretel. The children were always neglected by their step-mother. She didn’t love them and wanted to get rid of them and felt burden because of their presence at the house. There was the scarcity of food and famine in the region, so their father was unable to give food to the children. The step-mother was cruel and unkind to the children. That is why the stepmother made a plan to leave the children in the forest and for that reason she compelled her husband to leave the children in the forest. The children also understood the plan of their parents but didn’t do anything and accepted the bitter reality. They were suffering from hunger. The boy Hansel was very clever and he had gone out at night, filled his pocket with pebbles so as to scatter in the way of their trip to the forests.\n\n'
          'One day in the morning, the poor family had begun their trip to forest with the intention to leave the innocent children.  Hansel threw the pebbles on the road one by one. When they reached the forest, their father and mother left them were sleeping nearby the fireside. As the children woke up at night, found them alone and their parents had not there, so they waited until the moon rose and followed the road where the pebbles shone like silver pieces. They were able to come in to their house because of the pebbles. Their step-mother was restless to see them but the father was happy. The parents made another plan to leave them into more dense forest and the children had overhead the conversation of their parents but they couldn’t do anything as they were trapped in the room and given some breadcrumbs by the stepmother for the next day and went to a thick forest. But this time Hansel threw the pieces of bread on the road. When the father and mother came back home like before leaving the children in the forest in their deep sleep, the children woke up at night, followed the road but the pieces of bread were not there They missed the road, were tired and fell asleep under a tree. They followed a singing bird when they woke up. They reached a house. The roof of the house was made up of bread and the windows of sugar. The hungry children began to eat the house. An old woman came out from the house. She took them inside the house. They felt that it was heaven. The woman was wicked witch. She wanted to kill and eat them. So she imprisoned Hansel in the stable, gave good food to fatten him. But once, Gretel pushed the woman into the oven and bolted the door of oven and the woman burnt to death. Then Gretel being very happy freed her brother.\n\n'
          'The children were extremely excited when they found a lot of pearls and jewels in that house. They put it into their pockets and headed towards the home. But in their way there was a huge body of the water and began singing a son. Then the duck came and rescued them to the side of the river. When they walked a bit more, they knew that the river was familiar and while walking far they had seen their father’s home. They ran and found their father in the home but their step-mother was died. They gave the precious stone, jewels and pearls to their father and lived happily afterwards.\n\n'),
  Summary(
      id: 'l11',
      body:
          'Robert Coover’s story “The Gingerbread House” consists of forty-two numbered paragraphs which shows the parts of the story and it is an adoption of “Hansel and Gretel”. In the mid afternoon, an old man leads two children to the pine forest. The boy is dropping the pieces of bread and the girl is singing nursery songs and carrying a basket of flowers. The old man seems poor and miserable who wears the torn clothes is very poor, weak and thin. The children are also wearing torn clothes and walking with bare feet. The eyes of the old man are blue and his face is wrinkled. He is looking for the chance to leave the children in the thick forest. He feels guilty. Though he loves his children, he has no food to feed them. As they are walking, they encounter terrible witch who has worn black clothes. Her face is pale, her body is thin and twisted and her eyes are like burning coals. She cries madly and stretches her hand in the empty space. She catches a white dove and tears its red heart out.\n\n'
          'When they are on their way to their journey, they reach into the “Gingerbread House”. The house can be reached walking on the biscuits through the garden of sugared fruits. The house is made of sweets, chocolates and sugar. There is sticky I garden of sweets. The door of the house is heart shaped and red. It is shining like a ruby. The door is half-open. The place is sunny and beautiful. The air is fresh. There is river of honey and lollipops grow like daisies. The boy looks back and finds that the breadcrumbs that he drops are eaten up by the white birds. He is sad as his plan to return back home fails. The old man and the children spend the night in the forest. The next day, the old man tries to return back home silently but the children see and follow him. He pushes the girl and strikes the boy. The children weep but the old man returns home leaving the children in the dense forest.\n\n'
          'There are several obstacles in the story that are faced by the children.  Numerous problems and difficulties in the forest are common for them. However, they don’t lose their heart. They come to the gingerbread house. They fall on the sticky garden of sweets. They lick each other clean and are happy. The boy climbs up the roof of chocolate. They enjoy eating bread and sweets. Beyond the door of the house, there is the terrible sound of the witch flapping her black rags.\n\n'),
  Summary(
      id: 'l12',
      body:
          'It is transformation fairy tale written by Jacob and Wilhelm Grimm’s. “The Little Brother and the Little Sister” are all about the account of “Hansel and Gretel” in a different way. The children are not identified by their names but by their relation. So, the title is not “Hansel and Gretel” but “The Little Brother and The Little Sister”. In this fairy tale, a poor woodcutter lives by a great forest. He lives very difficult life with his second-wife and two children. Once, there is a famine (food shortage) and the family has no bread to eat. The step-mother is very cruel who forces her husband to leave the children in the forest. The children know the plan of their parents. The brother goes out of the house at night in the moonlight and fills his pocket with the shining pebbles. The next morning, the little brother and his sister are taken to the forest. On the way, the brother keeps on dropping the shining stones one by one. In the forest, the parents make a great fire and ask the children to wait until they come back. However, the parents don’t come back. The children are worried and they wait for the moon. When the moon shines at night, they came back home following the shining pebbles. The father who loves them very much becomes happy but the cruel step mother becomes angry.\n\n'
          'In the meantime, there is the scarcity of food. The step mother again compels the father to get rid of the children. They again take the children to the forest. This time the little brother drops the pieces of bread on the ways. The parents again make a great fire and come back home leaving the children in the forest. The little sister and her brother wait until the moon shines at night. However they don’t find the pieces of bread as they are eaten up by the birds. Then they are lost in the dense forest. They walk on and on for three days and finally they reach a house made of bread. The Window is made of sugar. When they begin to eat, an old witch comes and takes them inside the house she provides them with good food and nice bed. The next day, she imprisons the boy in the stable and makes the little sister work hard.\n\n'
          'After making Hansel fat, she wants to kill the brother and roast the little sister. One day the witch asks the sister to go into the oven to see if it is hot or not for the cakes. The clever sister says that she doesn’t know how to go into the oven. When the witch shows how to go in, the little girl pushes the witch inside the oven and closes the door of the oven. The witch burns to death. The little sister frees her little brother and they return home with a lot of jewels. The step mother is already dead. The father becomes happy and rich.\n\n'),
  Summary(
      id: 'l13',
      body:
          ' James Joyce’s “The Boarding House” is the suspense story which ends with the strategic techniques of Mrs. Mooney, central character in the story. She plays the significant role to settle the love affair of her young daughter and Mr. Doren with whom she had an affair and special relationship. The story is all about the character sketch of a strong determined woman named Mrs. Mooney and her persuasive strategies to settle her daughter’s affair with Mr. Doran.\n\n'
          'Mrs. Mooney is the daughter of a butcher. She marries a man who works for her father. After the death of her father, her husband starts drinking and taking money from the shop. He fights with her in front of the customers. After a short time, he finishes almost all the property and falls into heavy debt. One night, he runs after her with a knife to kill her. She escapes and saves her life spending the night in the neighboring house. Then, they can’t live together any more. Mrs Mooney takes her children and the remaining money of the shop and starts a Boarding House in Hardwick Street.\n\n'
          'Many tourists, musicians and the visitors from the city come to stay in the boarding house. The young men live and eat in the house. They talk about horses and sing songs on Sunday nights. Polly Mooney, the daughter of Mrs. Mooney also sings with them. Polly is a beautiful girl of nineteen with light soft hair and grey eyes. Her mother gives her housework to do so that she comes in contact with the young men. The intention of Mrs. Money is to trap a young man for her daughter. She watches her daughter and the young men carefully but none of them look serious in the beginning. When Mrs. Mooney notices something between Polly and one young man named Mr. Doran, she watches them carefully. Though people begin to talk about them, Mrs. Mooney keeps silent as she is waiting for the right time to talk about the affair openly. Finally, Mrs. Mooney makes a decision. She thinks that Mr. Doran must pa for his enjoyment. The money is not enough, he must marry her daughter.\n\n'
          'One evening, she calls her daughter about the affair. Though Polly seems uncomfortable, she tells every detail of their relationship. The mother calls Mr. Doran in her drawing room to talk about the affair. Mr. Doran is helpless and confused. Though he accepts his relationship with Polly, he does like to marry her. He knows that Polly is not educated and her family background is not good. People talk badly about her drunkard father and the bad reputation of the boarding house. His family will not accept her and his friends will laugh at him. He also knows that if he refuses to marry, he will lose his job. He remembers the hard face of his boss. Though he tries to be free by paying a lot of money as compensation, Mrs. Mooney makes him in a trap by saying that she doesn’t want to sell her daughter’s virtues. She uses strong reasons and persuasive strategies and reminds Mr. Doran of his happy moment with Polly. In this way, Mrs. Mooney very c1everly compels Mr. Doran to marry her daughter.\n\n'
          'At last, Mrs. Mooney called Mr. Doran to her house. She started to pressurize him to marry Poly at any case. But he refused at first. She even threatened him. But she reminded him all those happiest moments that he had spent with her daughter Polly. After remembering all the moments, he agreed to marry Polly. This is a type of strategy and technique from which Mrs. Mooney settled her daughter’s affair with Mr. Doren.\n\n'),
  Summary(
      id: 'l14',
      body:
          'The essay, “Two Long-Term Problems: Two Many People, Two Few Trees”, by a noted scholar Moti Nissani, is about two distinct yet inter-related, long-term problems. These two major problems, which are overpopulation and deforestation, are likely to destroy all the lives on our planet unless timely actions are taken.\n\n'
          'The essay starts with the world’s scientists concern over the earth’s environment. It is becoming much polluted. The air, water, and soil, which are regarded to be the most important things for the existence of any living species, are becoming poisonous and many kinds of plants and animals have already disappeared.\n\n'
          'Nissani opines the main reason for the degrading situation is overpopulation. It is constantly swinging up because people are living longer than in past and too many children are being born. He cites the example of Nepal, where the population has risen to 23 million from 9 million in less than 50 years. If the same trend continues unchecked, the population of Nepal will reach around 368 million after 140 years. Nepal is not the only case of this kind. The population is increasing everywhere except some countries which can be counted on finger tips. More people, in turn, use more natural resources, cause pollution, and bring changes in world climate.\n\n'
          'Meanwhile, the time for improvement is still within our reach. We can still control the situation though it is difficult to reverse it. We can minimise the problem by controlling our population. Education, especially to women, and information about how to avoid babies can help to reduce the population growth.\n\n'
          'As the population grows, forests are cut down for new farmlands and houses. The demand of rich people in the west for beef is also provoking people to change the forest into pasture-land. Besides, the demand of wood and paper products in developed countries is also adding fuel to the fire.\n\n'
          'When the trees are chopped down, the topsoil is destroyed. It leads to disastrous landslides and sudden flood. Deforestation also causes droughts, weather extremes, desertification, loss of wild species, and depletion of ozone layer.\n\n'
          'However, deforestation can also be controlled if the number of people will be controlled. Education, family planning and changes in the way we use wood are also important to control deforestation. For example, in Nepal the use of smokeless stoves can reduce the amount of firewood. The essayists reminds us that we know what changes we have to make but we are not clever or brave enough to make those changes. We need to apply what we know to control these two long-term problems.\n\n'),
  Summary(
      id: 'l15',
      body:
          'This is an essay written by the two American geographers M. Lilla and C. Bishop Barry present an exploration of the Karnali region which they did on foot for 15 adventurous months. After Christmas the two authors start their trip to know how Karnali is economically linked with Nepalgunj. Their fellow travelers bring medicinal herbs, hashish hand-knit sweaters and blankets in their baskets ~ to sell them in Nepalgunj.\n\n'
          'During their trip on foot, the two geographers see and learn many things about the life and culture of the people of Karnali region. On their way, a chhetri woman of 30 asks them whether they are going to Nepalgunj. According to her, her husband left her 15 years ago to find job in the plains the woman requests the authors to send him back if they find him. In a forest at 9,000 feet, they see some people processing Silajit sell it in Nepalgunj. Instead of processing it in their homes, they do it on the way because they have made a hurried trip to avoid a bad start. The people of the Karnali regions are superstitious as they believe that a bad star may have evil influence on them.\n\n'
          'They continue their journey, and notice some women cutting the branches of the ‘Sal’ trees to feed their goats. Almost all the trees have become bare. This shows that the people of Karnali zone are not aware of the possible environmental damage. They are ignorant about landslides, soil erosion, droughts etc. in the future. When the authors reach terai, they sit beside a campfire and listen to the night sounds of jackals, bats, mules and bullock carts. They walk on the paved streets and see the vehicles. Their fellow travelers or the people of Karnali region buy collon clothes, spice, jewelry, iron ware, aluminum and sweets to sell them in Karnali. The authors complete their exploration in Jumla.\n\n'
          'While they got back to the Terai region, the two American geographers learn a lot about the geographical condition and the life of people of the Karnali region. The authors observe all the seasons and the people who have been living in harmony with nature. They have been living very difficult life. As their cultivation can not support them, they have to involve them in trade. Some people go’to the plains in search of job. Thus, the people of Karnali zone are uneducated, conservative, and they earn their living by the various traditional works.\n\n'),
  Summary(
      id: 'l16',
      body:
          '‘I Have A Dream’ is an unforgettable speech delivered (given) by Martin Luther King to millions of American blacks and whites on August 28, 1963. This speech represents the hopes and dreams of all American blacks who have been struggling for their rights and freedom. Though the American constitution and the Declaration of Independence have promised equal rights, justice and freedom to all the blacks and whites, this is not implemented in practice. In American Societies, there is still strong racial discrimination, injustice, hatred and other inequalities between whites and blacks. The Blacks are hated, neglected and tortured in practice. In American societies, there is still strong racial discrimination, injustice, hatred and other inequalities between whites and blacks. The Blacks are hated, neglected and tortured because of their black skin. They are deprived of their rights, freedom, equality, and justice. They are treated to be slaves and are exiled in their own country. They live a very poor and miserable life among the rich whites. Only the whites enjoy the rights of life, liberty and the pursuit of happiness.\n\n'
          'Luther king addresses the American Blacks and says that they should continue their struggle until they establish equality, peace, and brotherhood in America. However, their struggle should be without violence. He says that they should fight for their rights without causing physical violence which may cause bitterness and hatred. They should follow the path and philosophy of Mahatma Gandhi. If they keep on struggling in a disciplined way, they will achieve their aims. Luther king hopes that one day; the chains of hatred, racial discrimination, injustice, and Inequalities will be broken. The new sun will rise with the rays of liberty, equality, peace, and brotherhood.\n\n'
          'Luther King urges that there should be an immediate change in the conception of whites. Racial and color discrimination will weaken the foundation of America. Luther King says that his dream is the dream of America. His dream is the dream of freedom, justice, and equality. The color of the skin is not important. What is important in humanity? Therefore one day, all discrimination and inequality will disappear. All the blacks and whites will walk together joining hands as brother and sister. At last, not only blacks, all the American people will be free. There will be sweet music of liberty, justice, and equality all over America.\n\n'),
  Summary(
      id: 'l17',
      body:
          'The writer Ilene Kantov is feminist writer who supports the most of the ideas of the women and their notion in the essay in the modern trend of globalization. She portrays a portrait of Lydia Pinkham and she goes on to tell about other business women who follow her footsteps. Lydia Pinkham combines her business with social service. She supports women’s rights, temperance and their social as well as economic reform. Her kind and beautiful face shines in the pages of papers to advertise her medicinal products to cure the diseases of women. She expects a militant feminist would support the business policy of Pinkham. She would certainly support women’s rights, independence as well as social and economic upliftment. She would react positively to Lydia’s advertising to champion women’s rights, temperance and fiscal reform. She would equally support the women’s advice on nutrition, exercise, hygiene and child rearing. She would, thus praise the activities of Pinkham and other women who tried to make the women race socially aware and economically independent. Lydia Pinkham and many other women of her time played different roles to promote women’s business. They competed with their male counterparts and didn’t hesitate to go to the court of law like male businessmen. A militant feminist would no doubt praise and support all these activities of women in this essay.\n\n'
          'However; there are some debatable statements of the writer which are not digestible for a militant feminist. Lydia Pinkham suggests her women customers not to go to the male physicians. A true feminist wouldn’t support such idea. She also wouldn’t support the altitudes of Helena and Elizabeth who attracted women to use cosmetics in the hope of getting married to European aristocrats. She would object the idea of limiting women’s business within their own race. A true feminist may think that men and women are interdependent. In the absence of either men or women, the world will not run. Thus, the business women should focus on the equality of men and women.\n\n'
          '“Women’s Business” differs in many ways from their male counterparts. The business women combined their business with social service. They displayed their images to advertise their products. The women offered their customers more than their products. They supported women’s rights, temperance, and social and economic reform. They gave advice to their customers about diet, exercise, hygiene etc. They printed reports for the women to cure physical problems, infertility nervousness, hysteria and even marital conflict. They used their images as women to promote their business. Helena and Elizabeth, for example, took advantage of their images as women to promote their business of cosmetics. Some business women tried to show their roles as mother and grandmother and some other developed their images as glamorous fashionable women. They advertised their products, promoted their business and earned a lot of money as well. Some women even invested some part of their profit into good works and social reform. However, women were more sex conscious. They helped only women and promoted traditional women’s skills. Lydia Pinkham, the leading American Business woman of that time advised her customers to avoid male physicians. In the realities of the market place, some business-women didn’t support feminism.\n\n'),
  Summary(
      id: 'l18',
      body:
          'Marsha Traugot wrote the essay “The Children who wait”, in the prevalent trend of child adoption in few decade in America context. Marsha Traugot suggests reasons for a new trend in adoption. Now a wider variety of Families can open their homes to children who in the past would have been leveled unadoptable. In setting forth the causes for this phenomenon, Traugot draws from specific case histories.\n\n'
          'The writer begins her essay with an example of a 51/2 years old black homeless girl named Tammy who is suffering from fatal alcohol syndrome which can stop her intellectual growth at any time. By this, Traugot wants to prove that she is not dealing with fiction but a specific case study. In the past, especially before 1960, the black, disabled, handicapped and sick children were unadoptable. Tammy has recently been legally freed for adoption which shows the changes that have taken place in the American adoption scene. Before 1960, only healthy white infants could be adopted. But now, the American adoption scene has been completely changed due to different civil rights movements, birth control, changing social values and social science research. Because of civil rights movements, the attitudes of American people towards Negro children changed. Due to birth control and legalized abortion, fewer unwanted babies were born. Even the unmarried women could keep their babies with them because of the changing social values. As a result, healthy babies were hardly available for adoption and people turned their attention to other children like Tammy.\n\n'
          'Due of massive growth of population, the number of homeless children is in the increasing trend. Between 1960 and 1978, the number of children in the foster home reached nearly half a million. Many states have no idea about the number of children who lived with their biological parents, who lived in foster homes and those children who could be adopted. If such children were left in the foster homes more than 18 months, they would suffer from different kinds of illnesses and social crimes. It would make their life more troublesome, complicated and worse. The politicians also wouldn’t invest any fund to begin new programs for such children as the children have no rights to vote. So, the homeless children were neglected and uncared. According to the child care specialists, the cost of keeping an average child in foster home was. \$3,600 to \$24,000. This shows that the foster home was expensive and cruel. The writer suggests that the social workers should change their attitudes. They should accept even disabled children for adoption. They should open child care centers and hold meetings.\n\n'
          'Now, the social workers write down the characteristics of the child and the profile of a suitable family, and then they try to match. To find the possible adoptive parents, the social workers first look to their lists. They give detailed information about the children to the regional exchange offices. They organize meetings and parties for children and possible parents to meet informally. If they still can’t find adopters by personal contact, they advertise on T.V. and publish the child’s profile in the newspapers. Thus, the child welfare specialists and the social workers can do a lot for the children who wait for adoption.\n\n'),
  Summary(
      id: 'l19',
      body:
          'The writer shows many differences between a traditional and modern society in matters of pregnancy, childbirth and childbearing. The traditional society is full of different customs, tradition~ rituals and superstition. A pregnant woman has to follow all such rites. She doesn’t get proper respect at home and society unless she gives birth to a child. Because of the customs, traditions and the culture of the traditional society, pregnant women are loved, cared and supported by her husbands, members of her family and all the relatives. Because of this, she doesn’t worry much about the possible pain and danger in childbirth.\n\n'
          'The traditional behaviors are responsible to increase her sense of security. However, in modern western societies, a pregnant woman is not cared like this. Since the people in the modern western society don’t believe much on different rites, traditions and superstitions, the pregnant woman is not attended by her husband and relatives. She is not free from mental burden. She is always worried about the possible danger and pain of the childbirth. She has to practice pregnantal exercises and make other preparations herself. She frequently visits doctors for advice and to get her pregnancy checked up. Her pregnancy is not given much importance by her family, relatives and the society.\n\n'
          'In the traditional eastern societies, the infant and mother mortality rate is higher because of the lack of modern methods and equipments. The traditional childbirths are conducted among various superstitions, customs, rites, rituals and traditions. The pregnant women don’t visit hospitals for check up. Because of this, a large number of women and their infants die untimely in the traditional society. In the modern western society, however, the infant and mother mortality rate is very low. The pregnant women shouldn’t carryon various customs, traditions and superstitions. They frequently visit doctors and follow their suggestions. They practice many modern methods and equipments for the childbirth. If the life of the mother or the infant is in danger, the doctors conduct operations to save them. Thus, the women in the modern society give birth very easily and safely among the modern methods and facilities.\n\n'
          'After the childbirth, the women in the traditional Eastern society are respected and praised much for their courage. Many people attend her with gifts to see the child and to congratulate the mother. People organize parties to celebrate the birth ceremony. There is feasting, singing and dancing. The mother is given permission to go to her mother’s house for few months. The whole family helps her to rear the child. However, there is no such system in the modern western society. In such society, there is no one t home to welcome the child and to praise the courage of the mother.\n\n'),
  Summary(
      id: 'l20',
      body:
          '“Gretel” is the contemporary adaptation of the writer Garrison Keillor. In this adaptation, the writer strongly states the statement given by Gretel in their going to forest. Gretel explores various feeling related to her bother Hansel, father and stepmother as well as the witch in the gingerbread house. Gretel is a radical or militant feminist. In the fairy tale “Gretel”, Keillor has sketched her character as a strong and dominant person. She blames the male characters who want to exploit her and her step-mother. She has to get half of the profits earned by selling the book according to the contract. However, the lawyers of Hansel put her under a spell and make her sign another contract. Then she gets very little money and the book is regarded to be pure imagination.\n\n'
          'Gretel is a benevolent as well as strong girl. She advocates the women’s rights and seems to be a feminist and wanted to raise her voice against the patriarchal society (male-dominated society). She wants to make the women aware and raises the voice against; injustice and inequality. She believes that women should get equal property right. When her brother makes a conspiracy not to share the money after selling the book, she becomes angry and evaluates that males are very cruel. She learns so many things from her own experience. The more she faces problems and suffers, the stronger she becomes. She is very sympathetic to the condition of women in the society. She is even sympathetic to the witch and her stepmother. She criticizes her father and brother. She always supports justice, equality and liberty. She is strong-minded, clever, brave and courageous girl.  She is very hopeful about her life and future. She thinks that her step mother and the witch are not completely wrong, but they show kind behavior towards the children due to the tradition. So tradition or faith is wrong. She is hopeful because she thinks that a girl like her may be the prey of various animals as well as birds. She may be bothered by fairies, shepherds, hermits as well. Gretel after all cope the circumstances with her wise sense and cleverness.\n\n'
          'Gretel expresses her different opinion to the cruel character too. Her step-mother is presented to be wicked and cruel; she is not so according to Gretel. Gretel says that it is the plan of the cruel father to leave her and her brother in the dense forest. She has to beat her brother to make him walk. She has to carry him on her back. Her father is a drunkard and the step mother can do nothing against his will. She blames her father and brother for being cruel and selfish. They live happily in a large building but Gretel and her step-mother have no home of their own. Gretel raises her hand against the male domination. She supports the principle that women should have the equal rights as men. She raises her voice against injustice. She supports feminism. She goes against male superiority. She proves that Hansel, being male, is unable to do anything. He is tired, nervous and afraid. She proves his weakness by carrying him on her back.\n\n'
          'Gretel criticizes her father also says he is selfish, unkind and irresponsible. He dominates his wife and doesn’t give her the share of property. Gretel is not afraid of anything. She has even sympathy to the witch. She thinks that the witch and the step-mother are not as bad as they are supposed to be. She feels sorry for the witch as she has pushed her without good reason. She thinks that the witch suffers most. In this way Gretel is a strong feminist who criticizes the existing male superiority in the society. She suffers because of the injustice of males. However, she is never hopeless. She believes that no children suffer permanently in the lap of nature. In this way. We can strongly state that Gretel is the strong supporter of justice, equality, and she often condemns (criticizes) injustice, male domination, sex discrimination and other social inequalities.\n\n'),
  Summary(
      id: 'l21',
      body:
          'W.B. Yeats’s play “Purgatory” depicts the restlessness of spirit after the death and bothers the living beings. Purgatory refers the place or state into which the soul passes after death to become purified of pardonable sins before going to heaven. In the play, there are two characters as old man and his son. Besides that there is dead spirit who hovers here and there for his part. The play basically concerns with the sorrow of the dead and the consequences of the crimes of the dead upon the living ones. The father of the old man committed a great crime by wasting the property by drinking and destroying the honorable house and deprived his son (the old man) from education and inheritance of the property. As a result, the old man, when he was sixteen, murdered his own father. In the play, the ruined house is often visited by the remorseful spirit of old man’s father and mother. The suffering spirit is not purified to enter the heaven because of its crimes and sins during alive.\n\n'
          'The groom (one who looks after the horse) marries a rich lady and the couples have a son. The lady dies after the birth of a child and the groom wastes her property by spending a lot and drinking. When the son becomes 16 years old, he murders his own father who burns the honored house, wastes the property and makes his son deprived of education and inheritance (legal rights) of the property. The son has become old now, and he has a bastard son (born out of wedlock). The scene of the play is a ruined house and a bare (naked) tree in the background. The old man and his bastard son stand in the moonlight before the house.\n\n'
          'During the anniversary of the old man’s mother’s wedding night, the old man finds that the suffering spirit visits the house again and again in the ruined house. The old man sees the ghost of his mother and hears the hoof-beats (sound from animal foots) of his father’s horse. The boy sees nothing and calls his father mad. The old man discloses the history of the destroyed house to his son. The boy steals the bag of money from the old man and tries to run away. They fight for the money that is scattered (spread) on the ground. The boy threatens to kill the old man. Now the old man is afraid of his own son who has become 16 years old. The old man thinks that his son may repeat the disgraceful tradition of his father. The old man decides to stop the polluted tradition which may last for generations. In the meantime, the boy also sees the spirit of his grandparents, and he becomes shocked. The old man suddenly stabs (kills by knife) his son to death to finish all the consequences. The stage is darkened and the bare tree appears “like a purified soul’ in the white light. The old man at the tree and explains why he has killed the boy. He wants to put an end to the chain of consequences, the polluted blood and its consequence. When he bends to pick up the scattered money, he again hears the hoof-beats of the dead spirit and sadly thinks that the consequence has not come to an end. He laments that he has killed his own father and son without any obvious purpose. Finally, the old man prays to God to free the tormented soul and calm them.\n\n'),
];
